


export const action_type = {

    SET_PRODUCTS :"SET_PRODUCTS",
    SET_PRODUCT_LIST :"SET_PRODUCT_LIST",
    SELECTED_PRODUCT :"SELECTED_PRODUCT",

    CATEGORY : "CATEGORY",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    INCREASE :"INCREASE",
    DECREASE : "DECREASE",
    GETURL :"GETURL",
    GETIMG: "GETIMG",
    
   

}